Repository wecode-bootcamp-korea/18-2nd-class200ok-frontend, pull requests merged in 2021-04, with the labels that each got.

#3 [18기 최송희] ADD : Lecture(강의)컴포넌트 레이아웃
  src/Components/Lecture/Lecture.js
  src/Components/Lecture/LectureForm.js
  src/index.js
Labels: Status: 리뷰 요청

#7 [18기 이대희] creatorNav 레이아웃 완료
  .env
  src/Pages/Creator/CreatorNav.js
  src/Routes.js
Labels: Status: 리뷰 요청

#4 [18기 이대희] add: 카카오 로그인 API 연동 및 레이아웃 구현, 백엔드 통신 완료
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/login.png
  src/config.js
Labels: Status: 리뷰 요청

#9 [18기 이대희]Modify: header, footer 레이아웃 기능 추가
  src/Pages/Creator/CreatorNav.js
Labels: Status: 리뷰 진행 중

#8 [18기 권영균] ADD : 목데이터추가/map을 이용해서 뿌리기 수정후 구현
  package-lock.json
  package.json
  public/data/ClassListData.json
  src/Components/Lecture/Lecture.js
  src/Components/Lecture/LectureForm.js
  src/Components/Pagenation/Buttons.js
  src/Components/Pagenation/Buttons.scss
  src/Components/Pagenation/Pagenation.js
  src/Components/Pagenation/Pagenation.scss
  src/Pages/Example/Example.js
  src/Pages/Filter/FirstModal.js
  src/Pages/Filter/FirstModal.scss
  src/Pages/Filter/SecondModal.js
  src/Pages/Filter/SecondModal.scss
  src/Pages/OpenSoon/OpenSoon.js
  src/Pages/OpenSoon/OpenSoon.scss
  src/Pages/OpenSoon/OpenSoonClass.js
  src/Pages/OpenSoon/OpenSoonClass.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 수정 요청

#10 [18기 이대희] add: 기본정보 레이아웃 기능 완료, 충돌해결
  .prettierrc
  src/Pages/Creator/Creatorinfo.js
  src/Routes.js
Labels: Status: 리뷰 요청

#11 [18기 이대희] add: creator 소개 이미지 업로드 레이아웃, 기능 구현, prettier 충돌해결
  .prettierrc
  package-lock.json
  src/Components/Lecture/CreatorInfoItem.js
  src/Pages/Creator/CreatorNav.js
  src/Pages/Creator/Creatorinfo.js
  src/Pages/Creator/Creatorintroduce.js
  src/Pages/Creator/create2.png
  src/Pages/Login/Login.js
  src/Pages/OpenSoon/OpenSoon.js
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [18기 이대희] creator Center 합본 / merge 요청
  public/data/openSoonModal.json
  src/Components/Lecture/CreatorInfoItem.js
  src/Components/Lecture/LectureForm.js
  src/Components/Modal/Modal.js
  src/Components/Modal/ModalForm.js
  src/Components/Nav/Nav.js
  src/Pages/Creator/Creator.js
  src/Pages/Creator/CreatorNav.js
  src/Pages/Creator/CreatorTitle.js
  src/Pages/Creator/Creatorinfo.js
  src/Pages/Creator/Creatorintroduce.js
  src/Pages/Login/Login.js
  src/Routes.js
Labels: Status: 리뷰 요청

#6 [18기 최송희] ADD : 강의(수강예정) 백엔드 통신 및 추가기능구현
  .prettierrc
  public/data/creatorPreview.json
  src/Components/Lecture/LectureForm.js
  src/Components/Modal/Modal.js
  src/Components/Modal/ModalLayout.js
  src/Pages/Creator/Creator.js
  src/Routes.js
Labels: Status: 리뷰 요청
